version: "3.3"

services:
  web:
    image: webdevops/php-nginx:alpine-php7
    working_dir: /app
    depends_on:
      - database
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DATE_TIMEZONE: "Europe/Paris"
      PHP_DISPLAY_ERRORS: 1

  database:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: geomiam
      MYSQL_ROOT_PASSWORD: root
